server.port=8283
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

servicego.host=https://servicego.udesk.cn
servicego.email=ServiceGo.demo@udesk.cn
servicego.api-token=51c8de11ba94e7a056b832414fdc8b15
servicego.entry-object-api-name=entryWorkOrder
servicego.entry-id-card-field=validIdCard

sms.api.token-url=https://sms-test.seres.cn/auth/accesstoken
sms.api.send-url=https://sms-test.seres.cn/api/sms/messages
sms.api.app-key=853432
sms.api.app-secret=983a4425209848419b7d3457d71b03dd
sms.api.consumer=50